export default function TermsOfServicePage() {
  return (
    <div className="bg-white min-h-screen">
      <div className="max-w-4xl mx-auto p-8 md:p-12">
        <p className="text-sm text-gray-500 mb-2">Last Updated: February 22, 2026</p>
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms of Service</h1>

        <div className="prose prose-gray max-w-none space-y-8">
          {/* AI DISCLAIMER */}
          <div className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
            <h2 className="text-xl font-bold text-amber-800 mt-0 mb-3">⚠️ Important: AI Disclaimer &amp; No Legal Advice</h2>
            <ul className="text-amber-900 space-y-2 mb-0">
              <li>EmployArmor uses <strong>artificial intelligence</strong> to analyze compliance requirements and generate documents.</li>
              <li>AI-generated content is for <strong>informational purposes only</strong>.</li>
              <li>All generated documents should be <strong>reviewed by a qualified attorney</strong> before use.</li>
              <li>EmployArmor is <strong>not a law firm</strong> and does not provide legal advice.</li>
              <li>Using EmployArmor does <strong>not</strong> create an attorney-client relationship.</li>
            </ul>
          </div>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">1. Acceptance of Terms</h2>
            <p className="text-gray-600">
              By accessing or using EmployArmor (&quot;the Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service. These Terms constitute a legally binding agreement between you and EmployArmor (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">2. Description of Service</h2>
            <p className="text-gray-600">
              EmployArmor is an AI-powered employment law compliance platform that helps organizations navigate AI hiring regulations, generate compliance documents, track consent requirements, and manage bias audits. The Service uses artificial intelligence to analyze regulatory requirements and produce tailored compliance materials.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">3. Not Legal Advice</h2>
            <p className="text-gray-600 font-semibold">
              EmployArmor is a compliance tool. We are not a law firm, and we do not provide legal advice. The information, documents, and assessments provided through our Service are for informational and compliance-management purposes only.
            </p>
            <p className="text-gray-600">
              You should consult with a qualified attorney before relying on any documents or guidance generated by the platform. Using EmployArmor does not create an attorney-client relationship between you and EmployArmor or any of its employees, contractors, or affiliates.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">4. AI-Generated Content</h2>
            <p className="text-gray-600">
              Documents, policies, notices, and other materials generated by EmployArmor are produced using artificial intelligence. While we strive for accuracy and regulatory alignment, AI-generated content may contain errors, omissions, or outdated information.
            </p>
            <p className="text-gray-600 font-semibold">
              All AI-generated documents should be reviewed by qualified legal counsel before use. You assume full responsibility for how you use any content generated by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">5. Account Responsibilities</h2>
            <ul className="text-gray-600 space-y-2">
              <li>You must provide accurate and complete registration information.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must notify us immediately of any unauthorized use of your account.</li>
              <li>You must be at least 18 years old to use the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">6. Subscription &amp; Billing</h2>
            <p className="text-gray-600">
              EmployArmor offers subscription plans on a monthly and annual basis. Payment is processed securely through Stripe. By subscribing, you authorize us to charge your payment method on a recurring basis.
            </p>
            <ul className="text-gray-600 space-y-2">
              <li>Subscriptions automatically renew unless cancelled before the end of the billing period.</li>
              <li>You may cancel your subscription at any time through your account settings.</li>
              <li>Refunds are handled on a case-by-case basis. Contact us at{" "}
                <a href="mailto:support@employarmor.com" className="text-blue-600 hover:text-blue-800">support@employarmor.com</a> for refund requests.
              </li>
              <li>We reserve the right to change pricing with 30 days&apos; notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">7. Acceptable Use</h2>
            <p className="text-gray-600">You agree not to:</p>
            <ul className="text-gray-600 space-y-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble any part of the Service</li>
              <li>Share your account credentials with unauthorized parties</li>
              <li>Use the Service to generate content for fraudulent or deceptive purposes</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
              <li>Resell or redistribute the Service without our written consent</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">8. Intellectual Property</h2>
            <p className="text-gray-600">
              The Service, including its design, features, code, and branding, is owned by EmployArmor and protected by intellectual property laws. You retain ownership of the data you input into the Service. Documents generated by the Service using your data are licensed to you for your business use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">9. Limitation of Liability</h2>
            <p className="text-gray-600">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, EMPLOYARMOR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.
            </p>
            <p className="text-gray-600">
              OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>
            <p className="text-gray-600">
              Without limiting the foregoing, EmployArmor makes no warranties regarding the accuracy, completeness, or legal sufficiency of any AI-generated content. You use the Service and its outputs at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">10. Disclaimer of Warranties</h2>
            <p className="text-gray-600">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">11. Termination</h2>
            <p className="text-gray-600">
              We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason at our discretion, with or without notice. You may terminate your account at any time. Upon termination, your right to use the Service ceases immediately. We may retain certain data as required by law or for legitimate business purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">12. Governing Law</h2>
            <p className="text-gray-600">
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the courts located in Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">13. Changes to These Terms</h2>
            <p className="text-gray-600">
              We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page and updating the &quot;Last Updated&quot; date. Your continued use of the Service after changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">14. Contact Us</h2>
            <p className="text-gray-600">
              If you have any questions about these Terms of Service, please contact us at{" "}
              <a href="mailto:support@employarmor.com" className="text-blue-600 hover:text-blue-800">support@employarmor.com</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
