export default function PrivacyPolicyPage() {
  return (
    <div className="bg-white min-h-screen">
      <div className="max-w-4xl mx-auto p-8 md:p-12">
        <p className="text-sm text-gray-500 mb-2">Last Updated: February 22, 2026</p>
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>

        <div className="prose prose-gray max-w-none space-y-8">
          {/* AI DISCLAIMER */}
          <div className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
            <h2 className="text-xl font-bold text-amber-800 mt-0 mb-3">⚠️ Important: AI Use Disclosure &amp; No Legal Advice</h2>
            <ul className="text-amber-900 space-y-2 mb-0">
              <li>EmployArmor uses <strong>artificial intelligence</strong> to analyze compliance requirements and generate documents.</li>
              <li>AI-generated content is for <strong>informational purposes only</strong>.</li>
              <li>All generated documents should be <strong>reviewed by a qualified attorney</strong> before use.</li>
              <li>EmployArmor is <strong>not a law firm</strong> and does not provide legal advice.</li>
              <li>Using EmployArmor does <strong>not</strong> create an attorney-client relationship.</li>
            </ul>
          </div>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">1. Introduction</h2>
            <p className="text-gray-600">
              EmployArmor (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates an AI-powered employment law compliance platform. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service. Please read this policy carefully. By using EmployArmor, you consent to the practices described herein.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">2. Information We Collect</h2>

            <h3 className="text-lg font-medium text-gray-800">Account Information</h3>
            <p className="text-gray-600">Name, email address, password, organization name, and billing details.</p>

            <h3 className="text-lg font-medium text-gray-800">Organization Data</h3>
            <p className="text-gray-600">Company details, industry, size, jurisdiction, and compliance configurations you provide.</p>

            <h3 className="text-lg font-medium text-gray-800">Employee &amp; Hiring Data</h3>
            <p className="text-gray-600">Information about employees and candidates that you input for compliance assessments, including roles, hiring processes, and AI tool usage in employment decisions.</p>

            <h3 className="text-lg font-medium text-gray-800">AI Tool Configurations</h3>
            <p className="text-gray-600">Details about AI tools used in your hiring and employment processes that you register for compliance tracking.</p>

            <h3 className="text-lg font-medium text-gray-800">Compliance Documents</h3>
            <p className="text-gray-600">Documents generated by or uploaded to the platform, including policies, notices, consent forms, and bias audit reports.</p>

            <h3 className="text-lg font-medium text-gray-800">Scan &amp; Assessment Results</h3>
            <p className="text-gray-600">Results from compliance scans, risk assessments, and regulatory analysis performed by our platform.</p>

            <h3 className="text-lg font-medium text-gray-800">Usage Data</h3>
            <p className="text-gray-600">Log data, device information, browser type, IP address, pages visited, and feature usage patterns.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">3. How We Use Your Information</h2>
            <ul className="text-gray-600 space-y-2">
              <li>Provide and maintain our compliance services</li>
              <li>Generate compliance documents, policies, and notices using AI</li>
              <li>Track consent and regulatory requirements</li>
              <li>Conduct compliance scans and risk assessments</li>
              <li>Provide training resources and compliance guidance</li>
              <li>Process payments and manage subscriptions</li>
              <li>Send service-related communications</li>
              <li>Improve and develop our platform</li>
              <li>Comply with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">4. AI-Generated Content</h2>
            <p className="text-gray-600">
              EmployArmor uses artificial intelligence to analyze hiring compliance requirements, generate legal documents (such as policies, notices, and consent forms), and assess regulatory risk. AI models process the data you provide to produce tailored compliance outputs.
            </p>
            <p className="text-gray-600 font-semibold">
              All AI-generated content is for informational purposes only and does not constitute legal advice. You should have all generated documents reviewed by a qualified attorney before use. EmployArmor is not a law firm and using our service does not create an attorney-client relationship.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">5. Third-Party Services</h2>
            <p className="text-gray-600">We use the following third-party services to operate our platform:</p>
            <ul className="text-gray-600 space-y-2">
              <li><strong>Supabase</strong> — Database hosting and authentication</li>
              <li><strong>Vercel</strong> — Application hosting and deployment</li>
              <li><strong>Stripe</strong> — Payment processing and subscription management</li>
              <li><strong>AI Models</strong> — Third-party AI services for document generation and compliance analysis</li>
            </ul>
            <p className="text-gray-600">
              Each third-party provider has its own privacy policy governing data handling. We encourage you to review their respective policies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">6. Data Retention &amp; Deletion</h2>
            <p className="text-gray-600">
              We retain your data for as long as your account is active or as needed to provide services. You may request deletion of your account and associated data at any time by contacting us at{" "}
              <a href="mailto:support@employarmor.com" className="text-blue-600 hover:text-blue-800">support@employarmor.com</a>.
              Upon account deletion, we will remove your personal data within 30 days, except where retention is required by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">7. Cookies</h2>
            <p className="text-gray-600">
              We use essential cookies for authentication and session management. We may also use analytics cookies to understand how our service is used. You can control cookie preferences through your browser settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">8. Your Rights (CCPA/GDPR)</h2>
            <p className="text-gray-600">Depending on your jurisdiction, you may have the following rights:</p>
            <ul className="text-gray-600 space-y-2">
              <li><strong>Access</strong> — Request a copy of the personal data we hold about you</li>
              <li><strong>Correction</strong> — Request correction of inaccurate data</li>
              <li><strong>Deletion</strong> — Request deletion of your personal data</li>
              <li><strong>Portability</strong> — Request a portable copy of your data</li>
              <li><strong>Opt-Out</strong> — Opt out of the sale of personal information (we do not sell personal data)</li>
              <li><strong>Non-Discrimination</strong> — We will not discriminate against you for exercising your rights</li>
            </ul>
            <p className="text-gray-600">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:support@employarmor.com" className="text-blue-600 hover:text-blue-800">support@employarmor.com</a>.
              We will respond within 30 days (or as required by applicable law).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">9. Children&apos;s Privacy</h2>
            <p className="text-gray-600">
              EmployArmor is not intended for use by individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected data from a person under 18, we will take steps to delete that information promptly.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">10. Security</h2>
            <p className="text-gray-600">
              We implement appropriate technical and organizational measures to protect your data. However, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">11. Changes to This Policy</h2>
            <p className="text-gray-600">
              We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on this page and updating the &quot;Last Updated&quot; date. Your continued use of EmployArmor after changes constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900">12. Contact Us</h2>
            <p className="text-gray-600">
              If you have any questions about this Privacy Policy, please contact us at{" "}
              <a href="mailto:support@employarmor.com" className="text-blue-600 hover:text-blue-800">support@employarmor.com</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
