import { NextRequest, NextResponse } from 'next/server'

const templates: Record<string, { filename: string; content: string; contentType: string }> = {
  'ai-disclosure-notice': {
    filename: 'AI-Disclosure-Notice-Template.txt',
    contentType: 'text/plain',
    content: `AI IN HIRING DISCLOSURE NOTICE
================================

[COMPANY NAME]
[ADDRESS]
[DATE]

NOTICE OF ARTIFICIAL INTELLIGENCE USE IN HIRING

Dear Applicant,

[Company Name] is committed to transparency in our hiring process. This notice is to inform you that we use artificial intelligence (AI) technology as part of our candidate evaluation process.

WHAT AI TOOLS WE USE
--------------------
We use the following AI-powered tools in our hiring process:

• [Tool Name 1] - [Brief description of purpose]
• [Tool Name 2] - [Brief description of purpose]
• [Add additional tools as needed]

HOW AI IS USED
--------------
These tools assist us in:

• [Describe specific use, e.g., "Screening resumes for relevant qualifications"]
• [Describe specific use, e.g., "Analyzing video interview responses"]
• [Describe specific use, e.g., "Assessing skills through automated testing"]

WHAT DATA IS COLLECTED
----------------------
The AI tools may collect and analyze the following information:

• Resume and application content
• [List other data types as applicable]
• [e.g., "Video and audio from recorded interviews"]
• [e.g., "Responses to skills assessments"]

HOW AI INFLUENCES DECISIONS
---------------------------
The output from these AI tools is one factor among many that our hiring team considers. AI-generated scores or recommendations are reviewed by human decision-makers before any employment decision is made. [Adjust this language based on your actual process]

YOUR RIGHTS
-----------
You have the right to:

• Request additional information about how AI was used in evaluating your application
• [Include state-specific rights as applicable]
• Contact us with questions about this notice

If you have questions or concerns about our use of AI in hiring, please contact:

[HR Contact Name]
[Email Address]
[Phone Number]

[Company Name] is an equal opportunity employer. Our AI tools are regularly monitored to ensure they do not discriminate based on race, color, religion, sex, national origin, age, disability, genetic information, or any other protected characteristic.

---

By continuing with your application, you acknowledge receipt of this notice.

Signature: _________________________

Printed Name: _________________________

Date: _________________________


© 2026 [Company Name]. Customize this template for your organization.
Generated by HireShield - hireshield.com
`,
  },
  'candidate-consent-form': {
    filename: 'Candidate-Consent-Form-Template.txt',
    contentType: 'text/plain',
    content: `CANDIDATE CONSENT FORM
AI-ASSISTED HIRING PROCESS
==========================

[COMPANY NAME]
[DATE]

CONSENT FOR AI-ASSISTED EVALUATION

I, _________________________________ (Candidate Name), acknowledge and consent to the following:

1. ACKNOWLEDGMENT OF AI USE
---------------------------
I have received and reviewed [Company Name]'s AI Disclosure Notice explaining the use of artificial intelligence in their hiring process.

2. CONSENT TO DATA PROCESSING
-----------------------------
I consent to [Company Name] using AI-powered tools to process the following information as part of my job application:

[ ] Resume and application materials
[ ] Video interview recordings
[ ] Skills assessment responses
[ ] [Other data types as applicable]

3. UNDERSTANDING OF AI'S ROLE
-----------------------------
I understand that:

• AI tools will assist in evaluating my candidacy
• AI-generated outputs are reviewed by human decision-makers
• AI analysis is one factor among many in hiring decisions
• I may request information about how AI was used in my evaluation

4. VOLUNTARY CONSENT
--------------------
I provide this consent voluntarily. I understand that:

• I may withdraw this consent at any time by contacting [HR Contact]
• Withdrawing consent may affect the company's ability to process my application
• [Include any state-specific opt-out rights]

5. NON-DISCRIMINATION STATEMENT
-------------------------------
I understand that [Company Name] is committed to ensuring their AI tools do not discriminate based on protected characteristics and regularly monitors for bias.


CANDIDATE SIGNATURE
-------------------

Signature: _________________________________

Printed Name: _________________________________

Email: _________________________________

Date: _________________________________

Position Applied For: _________________________________


FOR COMPANY USE ONLY
--------------------
Received by: _________________________________

Date Received: _________________________________

Application ID: _________________________________


---

© 2026 [Company Name]. Customize this template for your organization.
Generated by HireShield - hireshield.com
`,
  },
  'handbook-ai-policy': {
    filename: 'Employee-Handbook-AI-Policy-Template.txt',
    contentType: 'text/plain',
    content: `EMPLOYEE HANDBOOK SECTION
ARTIFICIAL INTELLIGENCE IN HUMAN RESOURCES
===========================================

[COMPANY NAME]
Effective Date: [DATE]

POLICY ON AI USE IN EMPLOYMENT DECISIONS

1. PURPOSE
----------
This policy describes [Company Name]'s use of artificial intelligence (AI) and automated decision-making technology in human resources processes, including hiring, performance evaluation, and other employment decisions.

2. SCOPE
--------
This policy applies to all applicants, employees, and contractors of [Company Name] in all locations where AI-powered HR tools are used.

3. OUR COMMITMENT
-----------------
[Company Name] is committed to:

• Transparency about our use of AI in employment decisions
• Ensuring AI tools do not discriminate against any protected group
• Maintaining human oversight of AI-assisted decisions
• Complying with all applicable laws and regulations

4. AI TOOLS WE USE
------------------
We currently use AI-powered tools in the following HR processes:

HIRING AND RECRUITING
• [Tool Name] for [purpose]
• [Tool Name] for [purpose]

PERFORMANCE MANAGEMENT
• [Tool Name] for [purpose]

OTHER HR FUNCTIONS
• [Tool Name] for [purpose]

[Update this section as tools change]

5. HOW AI IS USED
-----------------
AI tools assist our HR team by:

• Screening applications for minimum qualifications
• Identifying candidates who match job requirements
• Analyzing assessment results
• [Other uses as applicable]

AI recommendations are always reviewed by qualified HR professionals before employment decisions are made.

6. DATA COLLECTION AND USE
--------------------------
AI tools may collect and analyze:

• Application materials (resumes, cover letters)
• Assessment responses
• Interview recordings (where disclosed)
• Performance data
• Other job-related information

Data is used only for legitimate employment purposes and is handled in accordance with our Privacy Policy.

7. NON-DISCRIMINATION
---------------------
[Company Name] is committed to equal employment opportunity. Our AI tools are:

• Regularly tested for bias and discriminatory outcomes
• Monitored to ensure fair treatment across all demographic groups
• Subject to human review and override

We prohibit the use of AI in any way that discriminates based on race, color, religion, sex, national origin, age, disability, genetic information, veteran status, or any other protected characteristic.

8. EMPLOYEE RIGHTS
------------------
Employees and applicants have the right to:

• Be informed when AI is used in decisions affecting them
• Request information about how AI was used in their evaluation
• Raise concerns about AI decisions without fear of retaliation
• [Include state-specific rights as applicable]

9. REQUESTING INFORMATION
-------------------------
To request information about AI use in an employment decision affecting you, contact:

[HR Contact Name/Title]
[Email]
[Phone]

Requests will be responded to within [timeframe].

10. REPORTING CONCERNS
----------------------
If you believe an AI tool has produced an unfair or discriminatory outcome, report your concern to:

[HR Contact or Ethics Hotline]

All reports will be investigated promptly and confidentially.

11. POLICY UPDATES
------------------
This policy will be reviewed annually and updated as our AI tools change or as new regulations take effect. Employees will be notified of material changes.

12. QUESTIONS
-------------
Questions about this policy should be directed to [HR Contact].


Last Updated: [DATE]
Approved By: [NAME/TITLE]


---

© 2026 [Company Name]. Customize this template for your organization.
Generated by HireShield - hireshield.com
`,
  },
  'ai-tool-inventory': {
    filename: 'AI-Tool-Inventory-Template.csv',
    contentType: 'text/csv',
    content: `Tool Name,Vendor,Category,Purpose,Data Collected,AI Features,States Affected,Disclosure Required,Last Reviewed,Notes
LinkedIn Recruiter,LinkedIn,Sourcing,Candidate sourcing and outreach,Profile data; search behavior,AI matching; candidate recommendations,IL; CO; CA; NYC,Yes,2026-01-01,Review disclosure language
HireVue,HireVue,Video Interview,Video interview analysis,Video; audio; text responses,Facial analysis; tone analysis; word choice,IL; CO; CA; NYC,Yes,2026-01-01,Ensure pre-interview disclosure
Greenhouse,Greenhouse,ATS,Applicant tracking,Applications; resumes; notes,AI-powered matching (if enabled),Check configuration,Depends on features,2026-01-01,Verify which AI features are active
Indeed Assessments,Indeed,Assessment,Skills testing,Test responses; scores,AI-scored assessments,IL; CO; CA; NYC,Yes,2026-01-01,Include in candidate disclosure
[Add Your Tools],,,,,,,,,
[Add Your Tools],,,,,,,,,
[Add Your Tools],,,,,,,,,

INSTRUCTIONS:
1. List every tool used in your hiring process
2. Identify which tools use AI/ML/automated decision-making
3. Document what data each tool collects
4. Note which states' laws apply
5. Track disclosure requirements and last review date
6. Review and update quarterly

CATEGORIES: Sourcing; ATS; Video Interview; Assessment; Background Check; Chatbot; Other

Generated by HireShield - hireshield.com`,
  },
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const template = templates[slug]

  if (!template) {
    return NextResponse.json({ error: 'Template not found' }, { status: 404 })
  }

  return new NextResponse(template.content, {
    headers: {
      'Content-Type': template.contentType,
      'Content-Disposition': `attachment; filename="${template.filename}"`,
    },
  })
}
